name = "katelyatv"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 生产环境配置
[env.production]
name = "katelyatv"

# 生产环境 D1 数据库配置
[[env.production.d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "09df9e44-4abd-488f-9679-002780434b23"

# 生产环境变量
[env.production.vars]
# 补充之前顶层定义的变量到生产环境
USERNAME = "YJHxx2561"
PASSWORD = "yjh20050601"
NEXT_PUBLIC_ENABLE_REGISTER = "true"
# 原有生产环境变量
NEXT_PUBLIC_STORAGE_TYPE = "d1"
NEXT_PUBLIC_SITE_NAME = "KatelyaTV"
NEXT_PUBLIC_SITE_DESCRIPTION = "高性能影视播放平台"
NEXTAUTH_URL = "https://ktv.yjhup.com"
IMAGE_PROXY_ENABLED = "true"
CACHE_TTL = "3600"
CORS_ORIGIN = "*"
RATE_LIMIT_MAX = "100"
RATE_LIMIT_WINDOW = "60000"
HEALTH_CHECK_ENABLED = "true"
HEALTH_CHECK_INTERVAL = "30"
LOG_LEVEL = "info"
LOG_FORMAT = "json"
NODE_ENV = "production"

# 预览环境配置
[env.preview]
name = "katelyatv-preview"

# 预览环境 D1 数据库配置
[[env.preview.d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "09df9e44-4abd-488f-9679-002780434b23"

# 预览环境变量
[env.preview.vars]
# 补充需要的变量到预览环境
USERNAME = "YJHxx2561"
PASSWORD = "yjh20050601"
NEXT_PUBLIC_ENABLE_REGISTER = "true"
# 原有预览环境变量
NEXT_PUBLIC_STORAGE_TYPE = "d1"
NEXT_PUBLIC_SITE_NAME = "KatelyaTV"
NEXT_PUBLIC_SITE_DESCRIPTION = "高性能影视播放平台"
IMAGE_PROXY_ENABLED = "true"
NODE_ENV = "production"
